theme: jekyll-theme-minimal
title: Branden Morioka
![[prof pic](/Screen%20Shot%202018-06-25%20at%2010.32.30%20PM.png)
Format: ![Branden](https://github.com/bmorioka/branden.morioka.github.io/blob/master/Screen%20Shot%202018-06-25%20at%2010.32.30%20PM.png)
